version: '3.4'

services:
  products:
    image: wayfair-interviewing/products-service
    container_name: products-service
    build:
      context: products-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  payments:
    image: wayfair-interviewing/payments-service
    container_name: payments-service
    build:
      context: payments-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  cart-service:
    image: wayfair-interviewing/cart-service
    deploy:
      replicas: 2
    build:
      context: cart-service
      dockerfile: Dockerfile
    ports:
      - "8083"